language: android
jdk: oraclejdk8

before_install:
  - yes | sdkmanager "platform-tools" "tools" "platforms;android-27" "extras;android;m2repository"

before_script:
- chmod +x gradlew

script:
- ./gradlew build

after_success:
- ./gradlew test cobertura coveralls